// context/LanguageContext.tsx
"use client"
import { createContext, useContext, useState, useEffect } from 'react'

type Language = 'ar' | 'en'

type LanguageContextType = {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
    dir: 'rtl' | 'ltr'
}

const translations = {
    ar: {
        // عام
        'dashboard': 'لوحة المعلومات',
        'employees': 'الموظفين',
        'departments': 'الأقسام',
        'requests': 'الطلبات',
        'reports': 'التقارير',
        'attendance': 'الحضور',
        'settings': 'الإعدادات',
        'logout': 'تسجيل خروج',
        'add': 'إضافة',
        'edit': 'تعديل',
        'delete': 'حذف',
        'save': 'حفظ',
        'cancel': 'إلغاء',
        'search': 'بحث',
        'filter': 'تصفية',
        'all': 'الكل',
        'from': 'من',
        'to': 'إلى',
        'date': 'التاريخ',
        'reason': 'السبب',
        'actions': 'الإجراءات',
        'status': 'الحالة',
        'name': 'الاسم',
        'username': 'اسم المستخدم',
        'password': 'كلمة المرور',
        'email': 'البريد الإلكتروني',
        'phone': 'رقم الهاتف',
        'job_title': 'المسمى الوظيفي',
        'hire_date': 'تاريخ التعيين',
        'role': 'الدور',
        'department': 'القسم',
        'manager': 'مدير',
        'employee': 'موظف',
        'admin': 'مدير النظام',
        'hr': 'الموارد البشرية',
        'hr_manager': 'مدير موارد بشرية',
        'confirm': 'تأكيد',
        'close': 'إغلاق',
        'loading': 'جاري التحميل...',
        'no_data': 'لا توجد بيانات',
        'error': 'حدث خطأ',
        'success': 'تم بنجاح',
        'warning': 'تحذير',
        'info': 'معلومات',
        'view': 'عرض',
        'details': 'التفاصيل',
        'you': 'أنت',
        'none': 'لا يوجد',

        // حالات الطلبات
        'pending': 'قيد الانتظار',
        'approved': 'معتمدة',
        'rejected': 'مرفوضة',
        'pending_approvals': 'في انتظار الموافقات',
        'one_approval': 'موافقة واحدة',
        'pending_from': 'في انتظار',

        // أنواع الإجازات
        'leave_type_annual': 'سنوية',
        'leave_type_sick': 'مرضية',
        'leave_type_emergency': 'عارضة',
        'leave_type_unpaid': 'غير مدفوعة',
        'annual_leave': 'إجازة سنوية',
        'sick_leave': 'إجازة مرضية',
        'emergency_leave': 'إجازة عارضة',
        'unpaid_leave': 'إجازة غير مدفوعة',

        // الإحصائيات
        'total_employees': 'إجمالي الموظفين',
        'total_departments': 'إجمالي الأقسام',
        'employees_count': 'عدد الموظفين',
        'work_days': 'أيام العمل',
        'total_hours': 'إجمالي الساعات',
        'average': 'المتوسط',
        'hours_per_day': 'ساعة/يوم',

        // صفحات الموظفين
        'employee_page': 'صفحة الموظف',
        'my_attendance': 'حضوري',
        'my_leaves': 'إجازاتي',
        'my_overtime': 'أوفر تايمي',
        'my_permissions': 'إذوني',
        'my_corrections': 'تصحيح بصمتي',
        'leave_balance': 'رصيد الإجازات',
        'annual_total': 'الإجمالي السنوي',
        'used': 'مستخدم',
        'remaining': 'المتبقي',
        'total': 'الإجمالي',
        'check_in': 'تسجيل حضور',
        'check_out': 'تسجيل انصراف',
        'location_status': 'حالة الموقع',
        'getting_location': 'جاري الحصول على الموقع...',
        'location_success': 'تم الحصول على الموقع بنجاح',
        'location_not_available': 'الموقع غير متاح',
        'location_error': 'خطأ في الحصول على الموقع',
        'gps_not_supported': 'الـ GPS غير مدعوم في هذا المتصفح',
        'today_attendance': 'حضور اليوم',
        'attendance_history': 'سجل الحضور',
        'no_attendance_today': 'لا يوجد حضور اليوم',
        'select_dates_to_view': 'حدد التواريخ لعرض السجل',
        'new_request': 'طلب جديد',
        'leave_type': 'نوع الإجازة',
        'start_date': 'تاريخ البداية',
        'end_date': 'تاريخ النهاية',
        'hours': 'عدد الساعات',
        'permission_type': 'نوع الإذن',
        'expected_check_in': 'وقت الحضور المفترض',
        'expected_check_out': 'وقت الانصراف المفترض',
        'submit_request': 'تقديم الطلب',
        'previous_requests': 'الطلبات السابقة',
        'correction_for': 'تصحيح ليوم',
        'date_to_correct': 'التاريخ المطلوب تصحيحه',
        'request_leave': 'طلب إجازة',
        'request_overtime': 'طلب أوفر تايم',
        'request_permission': 'طلب إذن',
        'request_correction': 'طلب تصحيح',
        'new_leave_request': 'طلب إجازة جديد',
        'new_overtime_request': 'طلب أوفر تايم جديد',
        'new_permission_request': 'طلب إذن جديد',
        'new_correction_request': 'طلب تصحيح جديد',
        'reason_optional': 'السبب (اختياري)',
        'reason_required': 'السبب مطلوب',
        'select_dates': 'حدد التواريخ',
        'select_date_and_hours': 'حدد التاريخ وعدد الساعات',
        'select_date_and_reason': 'حدد التاريخ والسبب',
        'select_start_time': 'حدد وقت البداية',
        'insufficient_balance': 'رصيد غير كافٍ',
        'insufficient_emergency_balance': 'رصيد الإجازات العارضة غير كافٍ',
        'example_2_5': 'مثال: 2.5',
        'submitted': 'تاريخ التقديم',
        'confirm_delete': 'هل أنت متأكد من الحذف؟',
        'no_requests': 'لا توجد طلبات',

        // أنواع الإذن
        'one_hour': 'ساعة واحدة',
        'two_hours': 'ساعتين',
        'half_day': 'نصف يوم',

        // صفحات المدير
        'manager_page': 'لوحة تحكم المدير',
        'employee_requests': 'طلبات الموظفين',
        'managed_departments': 'الأقسام التي تديرها',
        'no_departments_managed': 'لا تدير أي أقسام',
        'approve': 'موافقة',
        'reject': 'رفض',
        'pending_requests': 'الطلبات المعلقة',
        'request_details': 'تفاصيل الطلب',
        'you_are_manager': 'أنت مدير لهذا الموظف',
        'approve_as_manager_and_hr': 'موافقة كمدير و HR',
        'approve_as_hr': 'موافقة كـ HR',
        'hr_approved': 'تمت موافقة HR',

        // صفحات الأدمن
        'admin_page': 'لوحة تحكم الموارد البشرية',
        'bulk_upload': 'رفع ملف Excel',
        'upload_template': 'تحميل نموذج Excel',
        'download_template': 'تحميل النموذج',
        'choose_file': 'اختر ملف',
        'start_upload': 'بدء الرفع',
        'upload_results': 'نتائج الرفع',
        'success_count': 'عدد الناجحين',
        'failed_count': 'عدد الفاشلين',
        'errors': 'الأخطاء',
        'upload_info': 'يمكنك رفع ملف Excel يحتوي على بيانات الموظفين',
        'required_columns': 'الأعمدة المطلوبة',
        'file': 'الملف',
        'records': 'السجلات',
        'no_data_to_upload': 'لا توجد بيانات للرفع',
        'missing_data': 'بيانات ناقصة',
        'error_processing': 'خطأ في معالجة',
        'add_department': 'إضافة قسم',
        'edit_department': 'تعديل قسم',
        'add_new_department': 'إضافة قسم جديد',
        'department_name': 'اسم القسم',
        'manage_managers': 'إدارة المدراء',
        'manage_managers_for': 'إدارة المدراء لقسم',
        'current_managers': 'المدراء الحاليون',
        'no_managers': 'لا يوجد مدراء',
        'add_manager': 'إضافة مدير',
        'select_manager': 'اختر مدير...',
        'confirm_delete_department': 'هل أنت متأكد من حذف هذا القسم؟',
        'confirm_remove_manager': 'هل أنت متأكد من إزالة هذا المدير؟',
        'all_requests': 'جميع الطلبات',
        'request_type': 'نوع الطلب',
        'filter_by_department': 'تصفية حسب القسم',
        'filter_by_type': 'تصفية حسب النوع',
        'filter_by_status': 'تصفية حسب الحالة',
        'export_report': 'تصدير التقرير',
        'attendance_report': 'تقرير الحضور',
        'absences_report': 'تقرير الغياب',
        'leaves_report': 'تقرير الإجازات',
        'view_report': 'عرض التقرير',
        'absent_days': 'أيام الغياب',
        'no_data_period': 'لا توجد بيانات في هذه الفترة',
        'no_attendance_data': 'لا توجد بيانات حضور',
        'add_employee': 'إضافة موظف',
        'add_new_employee': 'إضافة موظف جديد',
        'full_name': 'الاسم الكامل',
        'select_department': 'اختر القسم',
        'no_department': 'بدون قسم',
        'employee_added': 'تم إضافة الموظف بنجاح',
        'employee_updated': 'تم تعديل الموظف بنجاح',
        'employee_deleted': 'تم حذف الموظف بنجاح',
        'confirm_delete_employee': 'هل أنت متأكد من حذف هذا الموظف؟',
        'fill_required_fields': 'املأ جميع الحقول المطلوبة',
        'click_to_sort': 'اضغط على عنوان العمود للترتيب',
        'save_changes': 'حفظ التغييرات',

        // صفحة تسجيل الدخول
        'login': 'تسجيل الدخول',
        'remember_me': 'تذكرني',
        'login_button': 'دخول',
        'checking': 'جاري التحقق...',
        'invalid_credentials': 'بيانات الدخول غير صحيحة',
        'login_required': 'يجب تسجيل الدخول أولاً',
        'unauthorized': 'غير مصرح لك بالدخول',

        // تغيير كلمة المرور
        'change_password': 'تغيير كلمة المرور',
        'current_password': 'كلمة المرور الحالية',
        'new_password': 'كلمة المرور الجديدة',
        'confirm_password': 'تأكيد كلمة المرور',
        'save_new_password': 'حفظ كلمة المرور الجديدة',
        'password_changed_success': 'تم تغيير كلمة المرور بنجاح',
        'all_fields_required': 'جميع الحقول مطلوبة',
        'passwords_not_match': 'كلمة المرور الجديدة غير متطابقة',
        'password_min_length': 'كلمة المرور يجب أن تكون ٣ أحرف على الأقل',
        'connection_error': 'خطأ في الاتصال',

        // متفرقات
        'years_of_service': 'سنوات الخدمة',
        'years': 'سنوات',
        'days': 'أيام',
        'na': 'غير متوفر',
        'footer': 'جميع الحقوق محفوظة',
        'developed_by': 'تم التطوير بواسطة',
        'error_occurred': 'حدث خطأ',
    },
    en: {
        // General
        'dashboard': 'Dashboard',
        'employees': 'Employees',
        'departments': 'Departments',
        'requests': 'Requests',
        'reports': 'Reports',
        'attendance': 'Attendance',
        'settings': 'Settings',
        'logout': 'Logout',
        'add': 'Add',
        'edit': 'Edit',
        'delete': 'Delete',
        'save': 'Save',
        'cancel': 'Cancel',
        'search': 'Search',
        'filter': 'Filter',
        'all': 'All',
        'from': 'From',
        'to': 'To',
        'date': 'Date',
        'reason': 'Reason',
        'actions': 'Actions',
        'status': 'Status',
        'name': 'Name',
        'username': 'Username',
        'password': 'Password',
        'email': 'Email',
        'phone': 'Phone',
        'job_title': 'Job Title',
        'hire_date': 'Hire Date',
        'role': 'Role',
        'department': 'Department',
        'manager': 'Manager',
        'employee': 'Employee',
        'admin': 'Admin',
        'hr': 'HR',
        'hr_manager': 'HR Manager',
        'confirm': 'Confirm',
        'close': 'Close',
        'loading': 'Loading...',
        'no_data': 'No data available',
        'error': 'An error occurred',
        'success': 'Success',
        'warning': 'Warning',
        'info': 'Info',
        'view': 'View',
        'details': 'Details',
        'you': 'You',
        'none': 'None',

        // Request status
        'pending': 'Pending',
        'approved': 'Approved',
        'rejected': 'Rejected',
        'pending_approvals': 'Pending Approvals',
        'one_approval': 'One Approval',
        'pending_from': 'Pending from',

        // Leave types
        'leave_type_annual': 'Annual',
        'leave_type_sick': 'Sick',
        'leave_type_emergency': 'Emergency',
        'leave_type_unpaid': 'Unpaid',
        'annual_leave': 'Annual Leave',
        'sick_leave': 'Sick Leave',
        'emergency_leave': 'Emergency Leave',
        'unpaid_leave': 'Unpaid Leave',

        // Statistics
        'total_employees': 'Total Employees',
        'total_departments': 'Total Departments',
        'employees_count': 'Employees Count',
        'work_days': 'Work Days',
        'total_hours': 'Total Hours',
        'average': 'Average',
        'hours_per_day': 'hours/day',

        // Employee pages
        'employee_page': 'Employee Page',
        'my_attendance': 'My Attendance',
        'my_leaves': 'My Leaves',
        'my_overtime': 'My Overtime',
        'my_permissions': 'My Permissions',
        'my_corrections': 'My Corrections',
        'leave_balance': 'Leave Balance',
        'annual_total': 'Annual Total',
        'used': 'Used',
        'remaining': 'Remaining',
        'total': 'Total',
        'check_in': 'Check In',
        'check_out': 'Check Out',
        'location_status': 'Location Status',
        'getting_location': 'Getting location...',
        'location_success': 'Location obtained successfully',
        'location_not_available': 'Location not available',
        'location_error': 'Error getting location',
        'gps_not_supported': 'GPS not supported in this browser',
        'today_attendance': "Today's Attendance",
        'attendance_history': 'Attendance History',
        'no_attendance_today': 'No attendance today',
        'select_dates_to_view': 'Select dates to view history',
        'new_request': 'New Request',
        'leave_type': 'Leave Type',
        'start_date': 'Start Date',
        'end_date': 'End Date',
        'hours': 'Hours',
        'permission_type': 'Permission Type',
        'expected_check_in': 'Expected Check In',
        'expected_check_out': 'Expected Check Out',
        'submit_request': 'Submit Request',
        'previous_requests': 'Previous Requests',
        'correction_for': 'Correction for',
        'date_to_correct': 'Date to Correct',
        'request_leave': 'Request Leave',
        'request_overtime': 'Request Overtime',
        'request_permission': 'Request Permission',
        'request_correction': 'Request Correction',
        'new_leave_request': 'New Leave Request',
        'new_overtime_request': 'New Overtime Request',
        'new_permission_request': 'New Permission Request',
        'new_correction_request': 'New Correction Request',
        'reason_optional': 'Reason (optional)',
        'reason_required': 'Reason is required',
        'select_dates': 'Select dates',
        'select_date_and_hours': 'Select date and hours',
        'select_date_and_reason': 'Select date and reason',
        'select_start_time': 'Select start time',
        'insufficient_balance': 'Insufficient balance',
        'insufficient_emergency_balance': 'Insufficient emergency leave balance',
        'example_2_5': 'Example: 2.5',
        'submitted': 'Submitted',
        'confirm_delete': 'Are you sure you want to delete?',
        'no_requests': 'No requests',

        // Permission types
        'one_hour': 'One Hour',
        'two_hours': 'Two Hours',
        'half_day': 'Half Day',

        // Manager pages
        'manager_page': 'Manager Dashboard',
        'employee_requests': 'Employee Requests',
        'managed_departments': 'Managed Departments',
        'no_departments_managed': 'No departments managed',
        'approve': 'Approve',
        'reject': 'Reject',
        'pending_requests': 'Pending Requests',
        'request_details': 'Request Details',
        'you_are_manager': 'You are the manager for this employee',
        'approve_as_manager_and_hr': 'Approve as Manager & HR',
        'approve_as_hr': 'Approve as HR',
        'hr_approved': 'HR Approved',

        // Admin pages
        'admin_page': 'HR Dashboard',
        'bulk_upload': 'Bulk Upload',
        'upload_template': 'Download Excel Template',
        'download_template': 'Download Template',
        'choose_file': 'Choose File',
        'start_upload': 'Start Upload',
        'upload_results': 'Upload Results',
        'success_count': 'Success Count',
        'failed_count': 'Failed Count',
        'errors': 'Errors',
        'upload_info': 'Upload an Excel file containing employee data',
        'required_columns': 'Required columns',
        'file': 'File',
        'records': 'Records',
        'no_data_to_upload': 'No data to upload',
        'missing_data': 'Missing data',
        'error_processing': 'Error processing',
        'add_department': 'Add Department',
        'edit_department': 'Edit Department',
        'add_new_department': 'Add New Department',
        'department_name': 'Department Name',
        'manage_managers': 'Manage Managers',
        'manage_managers_for': 'Manage Managers for',
        'current_managers': 'Current Managers',
        'no_managers': 'No Managers',
        'add_manager': 'Add Manager',
        'select_manager': 'Select Manager...',
        'confirm_delete_department': 'Are you sure you want to delete this department?',
        'confirm_remove_manager': 'Are you sure you want to remove this manager?',
        'all_requests': 'All Requests',
        'request_type': 'Request Type',
        'filter_by_department': 'Filter by Department',
        'filter_by_type': 'Filter by Type',
        'filter_by_status': 'Filter by Status',
        'export_report': 'Export Report',
        'attendance_report': 'Attendance Report',
        'absences_report': 'Absences Report',
        'leaves_report': 'Leaves Report',
        'view_report': 'View Report',
        'absent_days': 'Absent Days',
        'no_data_period': 'No data for this period',
        'no_attendance_data': 'No attendance data',
        'add_employee': 'Add Employee',
        'add_new_employee': 'Add New Employee',
        'full_name': 'Full Name',
        'select_department': 'Select Department',
        'no_department': 'No Department',
        'employee_added': 'Employee added successfully',
        'employee_updated': 'Employee updated successfully',
        'employee_deleted': 'Employee deleted successfully',
        'confirm_delete_employee': 'Are you sure you want to delete this employee?',
        'fill_required_fields': 'Please fill all required fields',
        'click_to_sort': 'Click on column header to sort',
        'save_changes': 'Save Changes',

        // Login page
        'login': 'Login',
        'remember_me': 'Remember Me',
        'login_button': 'Login',
        'checking': 'Checking...',
        'invalid_credentials': 'Invalid credentials',
        'login_required': 'Please login first',
        'unauthorized': 'Unauthorized access',

        // Password change
        'change_password': 'Change Password',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'confirm_password': 'Confirm Password',
        'save_new_password': 'Save New Password',
        'password_changed_success': 'Password changed successfully',
        'all_fields_required': 'All fields are required',
        'passwords_not_match': 'New passwords do not match',
        'password_min_length': 'Password must be at least 3 characters',
        'connection_error': 'Connection error',

        // Miscellaneous
        'years_of_service': 'Years of Service',
        'years': 'years',
        'days': 'days',
        'na': 'N/A',
        'footer': 'All rights reserved',
        'developed_by': 'Developed by',
        'error_occurred': 'An error occurred',
    }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('ar')

    useEffect(() => {
        const savedLang = localStorage.getItem('language') as Language
        if (savedLang) {
            setLanguage(savedLang)
            document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr'
            document.documentElement.lang = savedLang
        }
    }, [])

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang)
        localStorage.setItem('language', lang)
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
        document.documentElement.lang = lang
    }

    const t = (key: string): string => {
        return translations[language][key as keyof typeof translations['ar']] || key
    }

    const dir = language === 'ar' ? 'rtl' : 'ltr'

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, dir }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}